title: QiaoY-Zhuo Homepage
page-top-title: QiaoY-Zhuo
top-section-bg-text: Be what you wanna be
home-subtitle: QiaoY-Zhuo&isfj;|&ensp;卓俏媛
copyright-text: '&copy; QiaoY-Zhuo 2024-2025. All Rights Reserved.'
